project:
  type: website
  output-dir: docs

website:
  title: "Sertaç EKER'in Analitik Labı"
  navbar:
    search: true
    left:
      - text: Anasayfa
        href: index.qmd
      - text: Hakkımda
        href: about.qmd
      - text: Gönderilerim
        href: posts.qmd
      - text: "MUY665 Ders Çıktıları"
        menu:
          - text: Ödevler
            href: portfolyo.qmd
          - text: Proje
            href: proje.qmd
            
    tools:
      - icon: github
        href: https://github.com/sertaceker26
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com/in/sertaceker1998/

  sidebar:
    - title: "Çalışmalar"
      style: "docked"
      search: true
      contents:
        - portfolyo.qmd
        - portfolyo/calisma1.qmd
        - portfolyo/calisma2.qmd  
        

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - MUY665 - Bahar 2026" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    toc-title: "İçindekiler"
    theme:
      light: flatly
      dark:  vapor
    css: styles.css
    smooth-scroll: true
    highlight-style: a11y
    code-copy: true
    code-overflow: wrap


editor: visual

